version: '3.9'
services:
  db:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: chat_app
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

  api:
    build: .
    restart: unless-stopped
    environment:
      DATABASE_URL: mysql://root:password@db:3306/chat_app
      JWT_SECRET: ${JWT_SECRET:-devsecret}
      PORT: 3000
      CORS_ORIGIN: ${CORS_ORIGIN:-http://localhost:5173}
      MESSAGE_RATE_LIMIT: 5
      MESSAGE_RATE_WINDOW_MS: 10000
    ports:
      - "3000:3000"
    depends_on:
      - db
    # wait for db then run
    command: sh -c "until mysqladmin ping -h db --silent; do sleep 1; done; npx prisma migrate deploy && node dist/index.js"

volumes:
  dbdata:

